#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

define('APP_PATH', __DIR__);

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php'; 

// import the Symfony Console Application 
use Symfony\Component\Console\Application;
use SGBot\Command;

$app = new Application('SGBot', '1.0');
$app->addCommands([
    new Command\MainCommand,
    new Command\ReportCommand,
]);
$app->run();